name: Lighthouse CI
# Audits live site after Render deploy; supports manual runs

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      send_email:
        description: "Send email report"
        type: boolean
        default: true
      to:
        description: "Override recipient email"
        required: false
        type: string
  repository_dispatch:
    types: [render_deploy_succeeded]
  workflow_run:
    workflows: ["Deploy to Render"]
    types: [completed]

concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile:
    name: Mobile Audit
    needs: [wait_for_deploy]
    if: github.event_name != 'workflow_run' || needs.wait_for_deploy.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      links: ${{ steps.lhci.outputs.links }}
      scores: ${{ steps.summarize.outputs.scores }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse (mobile)
        id: lhci
        uses: treosh/lighthouse-ci-action@v12
        continue-on-error: true
        with:
          configPath: ./lighthouserc-mobile.json
          uploadArtifacts: true
          artifactName: lighthouse-mobile
          temporaryPublicStorage: true
      - name: Debug list LHCI outputs (mobile)
        run: |
          echo "Listing .lighthouseci after mobile run" && ls -la .lighthouseci || true
      - name: Publish mobile reports to branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin lh-reports || true
          if git ls-remote --exit-code --heads origin lh-reports; then
            git checkout -B lh-reports origin/lh-reports
          else
            git checkout -B lh-reports
            echo "Lighthouse reports branch" > README.md
            git add README.md
            git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "chore(reports): init branch" || true
          fi
          mkdir -p reports/${GITHUB_RUN_ID}/mobile
          if [ -d .lighthouseci ] && ls -A .lighthouseci >/dev/null 2>&1; then
            cp -r .lighthouseci/* reports/${GITHUB_RUN_ID}/mobile/ || true
          else
            echo "No lighthouse output for mobile job" > reports/${GITHUB_RUN_ID}/mobile/NO_REPORTS.txt
          fi
          rm -rf reports/latest
          mkdir -p reports
          cp -r reports/${GITHUB_RUN_ID} reports/latest
          git add reports README.md || true
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "chore(reports): add mobile run ${GITHUB_RUN_ID}" || echo "no changes"
          for i in 1 2 3; do
            git pull --rebase origin lh-reports || true
            git push -u origin lh-reports && break || sleep 2
          done
      - name: Summarize scores (mobile)
        id: summarize
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.lighthouseci';
            const files = fs.existsSync(path) ? fs.readdirSync(path).filter(f => f.endsWith('.json')) : [];
            const result = [];
            for (const f of files) {
              const lhr = JSON.parse(fs.readFileSync(`${path}/${f}`, 'utf8'));
              const url = lhr.requestedUrl || lhr.finalUrl;
              const cats = lhr.categories;
              result.push({
                url,
                performance: cats.performance?.score ?? null,
                accessibility: cats.accessibility?.score ?? null,
                bestPractices: cats['best-practices']?.score ?? null,
                seo: cats.seo?.score ?? null,
              });
            }
            core.setOutput('scores', JSON.stringify(result));

  desktop:
    name: Desktop Audit
    needs: [wait_for_deploy, mobile]
    if: github.event_name != 'workflow_run' || needs.wait_for_deploy.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      links: ${{ steps.lhci.outputs.links }}
      scores: ${{ steps.summarize.outputs.scores }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse (desktop)
        id: lhci
        uses: treosh/lighthouse-ci-action@v12
        continue-on-error: true
        with:
          configPath: ./lighthouserc-desktop.json
          uploadArtifacts: true
          artifactName: lighthouse-desktop
          temporaryPublicStorage: true
      - name: Debug list LHCI outputs (desktop)
        run: |
          echo "Listing .lighthouseci after desktop run" && ls -la .lighthouseci || true
      - name: Publish desktop reports to branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin lh-reports || true
          if git ls-remote --exit-code --heads origin lh-reports; then
            git checkout -B lh-reports origin/lh-reports
          else
            git checkout -B lh-reports
            echo "Lighthouse reports branch" > README.md
            git add README.md
            git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "chore(reports): init branch" || true
          fi
          mkdir -p reports/${GITHUB_RUN_ID}/desktop
          if [ -d .lighthouseci ] && ls -A .lighthouseci >/dev/null 2>&1; then
            cp -r .lighthouseci/* reports/${GITHUB_RUN_ID}/desktop/ || true
          else
            echo "No lighthouse output for desktop job" > reports/${GITHUB_RUN_ID}/desktop/NO_REPORTS.txt
          fi
          rm -rf reports/latest
          mkdir -p reports
          cp -r reports/${GITHUB_RUN_ID} reports/latest
          git add reports README.md || true
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "chore(reports): add desktop run ${GITHUB_RUN_ID}" || echo "no changes"
          for i in 1 2 3; do
            git pull --rebase origin lh-reports || true
            git push -u origin lh-reports && break || sleep 2
          done
      - name: Summarize scores (desktop)
        id: summarize
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.lighthouseci';
            const files = fs.existsSync(path) ? fs.readdirSync(path).filter(f => f.endsWith('.json')) : [];
            const result = [];
            for (const f of files) {
              const lhr = JSON.parse(fs.readFileSync(`${path}/${f}`, 'utf8'));
              const url = lhr.requestedUrl || lhr.finalUrl;
              const cats = lhr.categories;
              result.push({
                url,
                performance: cats.performance?.score ?? null,
                accessibility: cats.accessibility?.score ?? null,
                bestPractices: cats['best-practices']?.score ?? null,
                seo: cats.seo?.score ?? null,
              });
            }
            core.setOutput('scores', JSON.stringify(result));

  email_report:
    name: Email Report
    if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_run' || (github.event_name == 'workflow_dispatch' && inputs.send_email == true)
    needs: [mobile, desktop]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare email body
        id: prep
        uses: actions/github-script@v7
        with:
          script: |
            function format(items) {
              if (!items || !items.length) return '- No data';
              return items.map(x => {
                const p = Math.round((x.performance ?? 0)*100);
                const a = Math.round((x.accessibility ?? 0)*100);
                const b = Math.round((x.bestPractices ?? 0)*100);
                const s = Math.round((x.seo ?? 0)*100);
                return `- ${x.url}\n  - Performance: ${p}\n  - Accessibility: ${a}\n  - Best-Practices: ${b}\n  - SEO: ${s}`;
              }).join('\n');
            }
            const mobileScores = JSON.parse(process.env.MOBILE_SCORES || '[]');
            const desktopScores = JSON.parse(process.env.DESKTOP_SCORES || '[]');
            const thresholds = { mobile: { performance: 70, accessibility: 90, bestPractices: 95, seo: 95 }, desktop: { performance: 85, accessibility: 90, bestPractices: 95, seo: 95 } };
            function below(items, t) {
              return items.some(x => {
                const p = Math.round((x.performance ?? 0)*100);
                const a = Math.round((x.accessibility ?? 0)*100);
                const b = Math.round((x.bestPractices ?? 0)*100);
                const s = Math.round((x.seo ?? 0)*100);
                return p < t.performance || a < t.accessibility || b < t.bestPractices || s < t.seo;
              });
            }
            const mobileFail = below(mobileScores, thresholds.mobile);
            const desktopFail = below(desktopScores, thresholds.desktop);
            const hasIssues = mobileFail || desktopFail;
            core.setOutput('subject', `Lighthouse Report${hasIssues ? ' [ALERT]' : ''}`);
            const mobileLinks = process.env.MOBILE_LINKS || 'see workflow artifacts';
            const desktopLinks = process.env.DESKTOP_LINKS || 'see workflow artifacts';
            const body = `Lighthouse Report${hasIssues ? ' (issues detected)' : ''}\n\nMobile\n\n${format(mobileScores)}\n\nLinks: ${mobileLinks}\n\nDesktop\n\n${format(desktopScores)}\n\nLinks: ${desktopLinks}\n\nRun: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}\nReports branch: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/tree/lh-reports/reports/${process.env.GITHUB_RUN_ID}`;
            require('fs').writeFileSync('email.md', body);
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server: ${{ secrets.MAIL_SERVER }}
          port: ${{ secrets.MAIL_PORT || 465 }}
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ steps.prep.outputs.subject }}
          from: ${{ secrets.MAIL_FROM || secrets.MAIL_USERNAME }}
          to: ${{ inputs.to || secrets.MAIL_TO || 'info.julita@gmail.com' }}
          html_body: file://email.md
        env:
          MOBILE_SCORES: ${{ needs.mobile.outputs.scores }}
          DESKTOP_SCORES: ${{ needs.desktop.outputs.scores }}
          MOBILE_LINKS: ${{ needs.mobile.outputs.links }}
          DESKTOP_LINKS: ${{ needs.desktop.outputs.links }}
  comment:
    name: PR Comment Summary
    if: github.event_name == 'pull_request'
    needs: [mobile, desktop]
    runs-on: ubuntu-latest
    steps:
      - name: Post Lighthouse summary comment
        uses: actions/github-script@v7
        with:
          script: |
            const mobileScores = JSON.parse(process.env.MOBILE_SCORES || '[]');
            const desktopScores = JSON.parse(process.env.DESKTOP_SCORES || '[]');
            const mobileLinks = process.env.MOBILE_LINKS;
            const desktopLinks = process.env.DESKTOP_LINKS;
            function fmt(items) {
              return items.map(x => `- ${x.url}\n  - Performance: ${Math.round((x.performance ?? 0)*100)}\n  - Accessibility: ${Math.round((x.accessibility ?? 0)*100)}\n  - Best-Practices: ${Math.round((x.bestPractices ?? 0)*100)}\n  - SEO: ${Math.round((x.seo ?? 0)*100)}`).join('\n');
            }
            const body = `### Lighthouse Summary\n\n**Mobile**\n\n${fmt(mobileScores)}\n\nLinks: ${mobileLinks || 'see workflow artifacts'}\n\n**Desktop**\n\n${fmt(desktopScores)}\n\nLinks: ${desktopLinks || 'see workflow artifacts'}`;
            const {owner, repo} = context.repo;
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.createComment({owner, repo, issue_number, body});
        env:
          MOBILE_SCORES: ${{ needs.mobile.outputs.scores }}
  wait_for_deploy:
    name: Wait For Render Deploy
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render deploy (API) or fallback to HTTP
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          set -e
          url="https://klymb.work/"
          echo "Waiting for deploy..."
          if [ -n "$RENDER_API_KEY" ] && [ -n "$RENDER_SERVICE_ID" ]; then
            echo "Using Render API to poll deploy for commit $HEAD_SHA on service $RENDER_SERVICE_ID"
            sudo apt-get update >/dev/null 2>&1 || true
            sudo apt-get install -y jq >/dev/null 2>&1 || true
            for i in {1..180}; do
              json=$(curl -sS -H "Authorization: Bearer $RENDER_API_KEY" \
                "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys?limit=10" || true)
              # Try to match deploy associated with this commit SHA (field names vary)
              deployId=$(printf "%s" "$json" | jq -r --arg sha "$HEAD_SHA" '[.[] | select(((.commitId // empty) == $sha) or ((.commit // empty) == $sha) or ((.gitCommitId // empty) == $sha))][0].id // empty')
              status=$(printf "%s" "$json" | jq -r --arg sha "$HEAD_SHA" '[.[] | select(((.commitId // empty) == $sha) or ((.commit // empty) == $sha) or ((.gitCommitId // empty) == $sha))][0].status // empty')
              echo "Attempt $i: commit=$HEAD_SHA deploy=${deployId:-not-found} status=${status:-unknown}"
              if [ -n "$deployId" ] && [ "$status" = "live" ]; then
                echo "Render deploy for commit $HEAD_SHA is live (id=$deployId). Allowing 30s for CDN propagation..."; sleep 30; exit 0; fi
              sleep 10
            done
            echo "Timed out waiting for Render deploy of commit $HEAD_SHA to become live via API"; exit 1
          else
            echo "RENDER_API_KEY/RENDER_SERVICE_ID not set; falling back to HTTP 200 polling at $url"
            for i in {1..60}; do
              code=$(curl -sS -o /dev/null -w "%{http_code}" "$url" || echo 000)
              echo "Attempt $i HTTP $code"
              if [ "$code" = "200" ]; then
                echo "Ready (HTTP 200). Allowing 10s for CDN warmup..."; sleep 10; exit 0; fi
              sleep 10
            done
            echo "Timed out waiting for HTTP 200 at $url"; exit 1
          fi
          DESKTOP_SCORES: ${{ needs.desktop.outputs.scores }}
          MOBILE_LINKS: ${{ needs.mobile.outputs.links }}
          DESKTOP_LINKS: ${{ needs.desktop.outputs.links }}
