name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *' # run nightly at 03:00 UTC
  workflow_dispatch: {}

jobs:
  mobile:
    name: Mobile Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse (mobile)
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./lighthouserc-mobile.json
          uploadArtifacts: true
          temporaryPublicStorage: true

  desktop:
    name: Desktop Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse (desktop)
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./lighthouserc-desktop.json
          uploadArtifacts: true
          temporaryPublicStorage: true
