name: Optimize Images

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    paths:
      - .github/optimize-images.trigger

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install sharp
        run: |
          npm i sharp@^0.33
      - name: Optimize homepage images (JPEG + WebP)
        run: |
          node - <<'NODE'
          const sharp = require('sharp');
          async function process(base){
            const jpg = `public/images/${base}.jpg`;
            const webp = `public/images/${base}.webp`;
            await sharp(jpg)
              .resize({width:1600, withoutEnlargement:true})
              .jpeg({quality:70, progressive:true})
              .toFile(jpg);
            await sharp(jpg)
              .resize({width:1600, withoutEnlargement:true})
              .webp({quality:70})
              .toFile(webp);
          }
          (async () => {
            await process('youngwoman_laptop2');
            await process('corp-hr3');
          })().catch(err => { console.error(err); process.exit(1); });
          NODE
      - name: Switch homepage to .webp sources
        run: |
          sed -i 's|/images/youngwoman_laptop2\.jpg|/images/youngwoman_laptop2.webp|g' src/app/page.tsx
          sed -i 's|/images/corp-hr3\.jpg|/images/corp-hr3.webp|g' src/app/page.tsx
      - name: Commit changes
        run: |
          branch="chore/optimize-images-${GITHUB_RUN_ID}"
          git checkout -b "$branch"
          git add public/images/youngwoman_laptop2.* public/images/corp-hr3.* src/app/page.tsx
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "chore(images): optimize homepage images (resize 1600, q=70), add WebP variants, and switch homepage to .webp"
          git push -u origin "$branch"
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(images): optimize homepage images (resize 1600, q=70) and add WebP variants"
          title: "Optimize homepage images"
          body: |
            This PR optimizes the homepage tile images by resizing to max-width 1600px and recompressing to quality=70.

            - Updated JPEGs in-place
            - Added `.webp` variants for future use

            After merge + deploy, Lighthouse's image delivery insight should improve.
          branch: "$branch"
          base: main
