name: Deploy to Render

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
      - name: Wait for version change via /api/version (fallback to BUILD_ID)
        env:
          SITE_URL: https://klymb.work
        run: |
          set -e
          echo "Fetching baseline version with cache-busting"
          TS=$(date +%s%N)
          BASE_JSON=$(curl -fsSL -H 'Cache-Control: no-cache' "$SITE_URL/api/version?ts=$TS" || echo '{}')
          BASE_COMMIT=$(printf "%s" "$BASE_JSON" | jq -r '.commit // empty')
          BASE_BUILD=$(printf "%s" "$BASE_JSON" | jq -r '.buildId // empty')
          echo "Baseline: commit=${BASE_COMMIT:-n/a} buildId=${BASE_BUILD:-n/a}"
          echo "Waiting for version change..."
          for i in $(seq 1 180); do
            TS_LOOP=$(date +%s%N)
            CUR_JSON=$(curl -fsSL -H 'Cache-Control: no-cache' "$SITE_URL/api/version?ts=$TS_LOOP" || echo '{}')
            CUR_COMMIT=$(printf "%s" "$CUR_JSON" | jq -r '.commit // empty')
            CUR_BUILD=$(printf "%s" "$CUR_JSON" | jq -r '.buildId // empty')
            echo "Attempt $i: commit=${CUR_COMMIT:-n/a} buildId=${CUR_BUILD:-n/a}"
            if { [ -n "$CUR_COMMIT" ] && [ "$CUR_COMMIT" != "$BASE_COMMIT" ]; } || { [ -n "$CUR_BUILD" ] && [ "$CUR_BUILD" != "$BASE_BUILD" ]; }; then
              echo "Detected version change (commit/buildId). Allowing 45s for CDN propagation..."; sleep 45; exit 0; fi
            # Fallback: BUILD_ID file if version route unavailable
            CUR_ID=$(curl -fsSL -H 'Cache-Control: no-cache' "$SITE_URL/_next/static/BUILD_ID?ts=$TS_LOOP" || true)
            if [ -n "$CUR_ID" ] && [ "$CUR_ID" != "unknown" ] && [ "$CUR_ID" != "$BASE_BUILD" ]; then
              echo "Detected fallback BUILD_ID change ($CUR_ID). Allowing 45s for CDN propagation..."; sleep 45; exit 0; fi
            sleep 10
          done
          echo "Timed out waiting for version change at $SITE_URL" >&2
          exit 1
      - name: Notify Lighthouse via repository_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner_repo=${GITHUB_REPOSITORY}
          echo "Dispatching render_deploy_succeeded to $owner_repo"
          curl -sS -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${owner_repo}/dispatches" \
            -d "{\"event_type\":\"render_deploy_succeeded\",\"client_payload\":{\"commit\":\"${GITHUB_SHA}\"}}"
