name: Deploy to Render

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
      - name: Wait for site BUILD_ID to change (live)
        env:
          SITE_URL: https://klymb.work
        run: |
          set -e
          echo "Fetching current BUILD_ID from $SITE_URL/_next/static/BUILD_ID"
          BASE_ID=$(curl -fsS "$SITE_URL/_next/static/BUILD_ID" || echo unknown)
          echo "Baseline BUILD_ID: $BASE_ID"
          echo "Waiting for BUILD_ID to change (indicates new version is live)..."
          for i in $(seq 1 180); do
            CUR_ID=$(curl -fsS "$SITE_URL/_next/static/BUILD_ID" || echo unknown)
            echo "Attempt $i: BUILD_ID=$CUR_ID"
            if [ -n "$CUR_ID" ] && [ "$CUR_ID" != "$BASE_ID" ] && [ "$CUR_ID" != "unknown" ]; then
              echo "Detected new BUILD_ID ($CUR_ID). Allowing 30s for CDN propagation..."; sleep 30; exit 0; fi
            sleep 10
          done
          echo "Timed out waiting for BUILD_ID to change at $SITE_URL" >&2
          exit 1
      - name: Notify Lighthouse via repository_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner_repo=${GITHUB_REPOSITORY}
          echo "Dispatching render_deploy_succeeded to $owner_repo"
          curl -sS -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${owner_repo}/dispatches" \
            -d "{\"event_type\":\"render_deploy_succeeded\",\"client_payload\":{\"commit\":\"${GITHUB_SHA}\"}}"
